[package]
name = "splits-io-api"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
edition = "2018"
documentation = "https://docs.rs/splits-io-api/"
repository = "https://github.com/LiveSplit/split-io-api"
license = "Apache-2.0/MIT"
description = "Bindings to the splits.io API for Rust."
readme = "README.md"
keywords = ["splits-io", "speedrun", "livesplit", "web", "async"]
categories = ["network-programming", "api-bindings"]
include = [
    "/src/*",
    "/Cargo.toml",
    "/CHANGELOG.md",
    "/LICENSE-APACHE",
    "/LICENSE-MIT",
    "/README.md"
]

[badges]

[dependencies]
futures-util = "0.3.1"
http = "0.2.0"
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
snafu = { version = "0.6.0", default-features = false, features = ["std"] }
url = "2.1.0"
uuid = { version = "0.8.1", default-features = false, features = ["serde"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bytes = "0.5.2"
hyper = { version = "0.13.0", default-features = false, features = ["tcp"] }
hyper-tls = "0.4.0"
tokio-tungstenite = { git = "https://github.com/dbcfd/tokio-tungstenite", branch = "tokio2-released", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures-channel = "0.3.1"
js-sys = "0.3.31"
wasm-bindgen = "0.2.51"
wasm-bindgen-futures = "0.4.4"
web-sys = { version = "0.3.32", features = ["Response", "Window", "RequestInit", "AbortSignal", "ObserverCallback", "ReferrerPolicy", "RequestCache", "RequestCredentials", "RequestInit", "RequestMode", "RequestRedirect", "Headers", "WebSocket"] }

[dev-dependencies]
tokio = { version = "0.2", features = ["io-std", "macros"] }
