[package]
name = "splits-io-api"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
edition = "2018"
documentation = "https://docs.rs/splits-io-api/"
repository = "https://github.com/LiveSplit/split-io-api"
license = "Apache-2.0/MIT"
description = "Bindings to the splits.io API for Rust."
readme = "README.md"
keywords = ["splits.io", "speedrun", "livesplit", "web", "async"]

[dependencies]
hyper = "0.13.0-alpha.1"
hyper-rustls = "0.18.0-alpha.1"
snafu = "0.5.0"
serde = { version = "1.0.99", features = ["derive"] }
uuid = { version = "0.7.4", features = ["serde"] }
url = "2.1.0"
serde_json = "1.0.40"
futures-preview = "0.3.0-alpha.18"
tokio-tungstenite = { git = "https://github.com/dbcfd/tokio-tungstenite", branch = "tokio2", default-features = false }

[dev-dependencies]
tokio = "0.2.0-alpha.4"
